<a href="https://colab.research.google.com/github/mwcastellan/Data-Analytics-con-Python/blob/main/PreEntrega_MWC.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pre Entrega - Marcelo Walter Castellan

## Etapa 1: Recopilación y Preparación de Datos (Clases 1 a 4)

In [ ]:
# Importar la librería Pandas
import pandas as pd

### Cargar Datasets

In [ ]:
def cargar_dataset(link):
  # Usamos regex para extraer el file_id del link
  file_id = link.split('/d/')[1].split('/')[0]

  # Con ese file_id generamos la url
  url = f"https://drive.google.com/uc?id={file_id}"

  # Finalmente lo importamos usando el método read_csv() con la url generada
  df = pd.read_csv(url)
  return df

#### Clientes

In [ ]:
# Link generado al compartir el archivo clientes.csv
link = "https://drive.google.com/file/d/1pyNXpqnOauR5tWJWj9f8C15Ygn5HmdWT/view?usp=drive_link"
df_clientes = cargar_dataset(link)

#### Ventas

In [ ]:
# Link generado al compartir el archivo ventas.csv
link = "https://drive.google.com/file/d/1dpvV5iOAKyD7QZX8gwAZVZIefWGpnTKM/view?usp=drive_link"
df_ventas = cargar_dataset(link)

#### Marketing

In [ ]:
# Link generado al compartir el archivo marketing.csv
link = "https://drive.google.com/file/d/1NV-ICitmc8HQjhNEuUcgKqvajoBbNBT5/view?usp=drive_link"
df_marketing = cargar_dataset(link)

### Análisis de Datos

In [ ]:
# Análisis de Datos
print("Clientes: --- Primeras filas del dataset ---")
display(df_clientes.head())
# Obtener información general (tipos de datos y memoria)
print("\n--- Información General ---")
df_clientes.info()
# Resumen estadístico de columnas numéricas
print("\n--- Resumen Estadístico ---")
display(df_clientes.describe())
# Ver las dimensiones del DataFrame (Filas, Columnas)
print(f"\nDimensiones del dataset: {df_clientes.shape}")

print("=====================================================================")

print("Ventas: --- Primeras filas del dataset ---")
display(df_ventas.head())
# Obtener información general (tipos de datos y memoria)
print("\n--- Información General ---")
df_ventas.info()
# Resumen estadístico de columnas numéricas
print("\n--- Resumen Estadístico ---")
display(df_ventas.describe())
# Ver las dimensiones del DataFrame (Filas, Columnas)
print(f"\nDimensiones del dataset: {df_ventas.shape}")

print("=====================================================================")

print("Marketing: --- Primeras filas del dataset ---")
display(df_marketing.head())
# Obtener información general (tipos de datos y memoria)
print("\n--- Información General ---")
df_marketing.info()
# Resumen estadístico de columnas numéricas
print("\n--- Resumen Estadístico ---")
display(df_marketing.describe())
# Ver las dimensiones del DataFrame (Filas, Columnas)
print(f"\nDimensiones del dataset: {df_marketing.shape}")

print("=====================================================================")

Clientes: --- Primeras filas del dataset ---

   id_cliente               nombre  edad         ciudad  ingresos
0           1      Aloysia Screase    44  Mar del Plata  42294.68
1           2  Kristina Scaplehorn    25        Posadas  24735.04
2           3       Filip Castagne    50    Resistencia  35744.85
3           4          Liuka Luard    39   Bahía Blanca  27647.96
4           5        Dore Cockshtt    28        Rosario  28245.65

--- Información General ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 567 entries, 0 to 566
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   id_cliente  567 non-null    int64
 1   nombre      567 non-null    object
 2   edad        567 non-null    int64
 3   ciudad      567 non-null    object
 4   ingresos    567 non-null    float64
dtypes: float64(1), int64(2), object(2)
memory usage: 22.3+ KB

--- Resumen Estadístico ---

       id_cliente        edad      ingresos
count  567.000000  567.000000    567.000000
mean   284.000000   37.940035  34668.739012
std    163.823075   10.202885  12974.531446
min      1.000000   20.000000    170.290000
25%    142.500000   30.000000  26015.240000
50%    284.000000   37.000000  35066.830000
75%    425.500000   43.000000  42457.100000
max    567.000000   81.000000  88053.010000

Dimensiones del dataset: (567, 5)
=====================================================================
Ventas: --- Primeras filas del dataset ---

,id_venta,producto,precio,cantidad,fecha_venta,categoria
0,792,Cuadro decorativo,$69.94,5.0,02/01/2024,Decoración
1,811,Lámpara de mesa,$105.10,5.0,02/01/2024,Decoración
2,1156,Secadora,$97.96,3.0,02/01/2024,Electrodomésticos
3,1372,Heladera,$114.35,8.0,02/01/2024,Electrodomésticos
4,1546,Secadora,$106.21,4.0,02/01/2024,Electrodomésticos

--- Información General ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3035 entries, 0 to 3034
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   id_venta     3035 non-null   int64
 1   producto     3035 non-null   object
 2   precio       3033 non-null   object
 3   cantidad     3033 non-null   float64
 4   fecha_venta  3035 non-null   object
 5   categoria    3035 non-null   object
dtypes: float64(1), int64(1), object(4)
memory usage: 142.4+ KB

--- Resumen Estadístico ---

          id_venta     cantidad
count  3035.000000  3033.000000
mean   1499.851400     6.496538
std     866.465379     3.457250
min       1.000000     1.000000
25%     748.500000     3.000000
50%    1502.000000     7.000000
75%    2249.500000     9.000000
max    3000.000000    12.000000

Dimensiones del dataset: (3035, 6)
=====================================================================
Marketing: --- Primeras filas del dataset ---

   id_campanha         producto  canal  costo fecha_inicio   fecha_fin
0           74  Adorno de pared     TV   4.81   20/03/2024  03/05/2024
1           12           Tablet   RRSS   3.40   26/03/2024  13/05/2024
2           32  Lámpara de mesa  Email   5.54   28/03/2024  20/04/2024
3           21       Smartphone   RRSS   6.37   29/03/2024  16/05/2024
4           58         Alfombra  Email   4.25   31/03/2024  05/05/2024

--- Información General ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 90 entries, 0 to 89
Data columns (total 6 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_campanha   90 non-null     int64
 1   producto      90 non-null     object
 2   canal         90 non-null     object
 3   costo         90 non-null     float64
 4   fecha_inicio  90 non-null     object
 5   fecha_fin     90 non-null     object
dtypes: float64(1), int64(1), object(4)
memory usage: 4.3+ KB

--- Resumen Estadístico ---

       id_campanha      costo
count    90.000000  90.000000
mean     45.500000   4.928667
std      26.124701   0.947750
min       1.000000   2.950000
25%      23.250000   4.372500
50%      45.500000   4.900000
75%      67.750000   5.562500
max      90.000000   7.390000

Dimensiones del dataset: (90, 6)
=====================================================================

### Calidad de Datos

In [ ]:
# Calidad de Datos
print("Clientes: --- Calidad de Datos ---")
# Identificar valores nulos por columna
print("--- Valores Nulos por Columna ---")
nulos = df_clientes.isnull().sum()
print(nulos)
# Identificar filas duplicadas
duplicados = df_clientes.duplicated().sum()
print(f"\nCantidad de registros duplicados: {duplicados}")
# Documentación del estado inicial
print("\n--- Resumen de Calidad de Datos ---")
if nulos.sum() == 0 and duplicados == 0:
    print("El dataset no presenta valores nulos ni duplicados iniciales.")
else:
    print(f"Se detectaron {nulos.sum()} valores faltantes en total.")
    print(f"Se detectaron {duplicados} filas repetidas que requieren atención.")
print("=====================================================================")

print("Ventas: --- Calidad de Datos ---")
# Identificar valores nulos por columna
print("--- Valores Nulos por Columna ---")
nulos = df_ventas.isnull().sum()
print(nulos)
# Identificar filas duplicadas
duplicados = df_ventas.duplicated().sum()
print(f"\nCantidad de registros duplicados: {duplicados}")
# Documentación del estado inicial
print("\n--- Resumen de Calidad de Datos ---")
if nulos.sum() == 0 and duplicados == 0:
    print("El dataset no presenta valores nulos ni duplicados iniciales.")
else:
    print(f"Se detectaron {nulos.sum()} valores faltantes en total.")
    print(f"Se detectaron {duplicados} filas repetidas que requieren atención.")
print("=====================================================================")

print("Marketing: --- Calidad de Datos ---")
# Identificar valores nulos por columna
print("--- Valores Nulos por Columna ---")
nulos = df_marketing.isnull().sum()
print(nulos)
# Identificar filas duplicadas
duplicados = df_marketing.duplicated().sum()
print(f"\nCantidad de registros duplicados: {duplicados}")
# Documentación del estado inicial
print("\n--- Resumen de Calidad de Datos ---")
if nulos.sum() == 0 and duplicados == 0:
    print("El dataset no presenta valores nulos ni duplicados iniciales.")
else:
    print(f"Se detectaron {nulos.sum()} valores faltantes en total.")
    print(f"Se detectaron {duplicados} filas repetidas que requieren atención.")
print("=====================================================================")

Clientes: --- Calidad de Datos ---
--- Valores Nulos por Columna ---
id_cliente    0
nombre        0
edad          0
ciudad        0
ingresos      0
dtype: int64

Cantidad de registros duplicados: 0

--- Resumen de Calidad de Datos ---
El dataset no presenta valores nulos ni duplicados iniciales.
=====================================================================
Ventas: --- Calidad de Datos ---
--- Valores Nulos por Columna ---
id_venta       0
producto       0
precio         2
cantidad       2
fecha_venta    0
categoria      0
dtype: int64

Cantidad de registros duplicados: 35

--- Resumen de Calidad de Datos ---
Se detectaron 4 valores faltantes en total.
Se detectaron 35 filas repetidas que requieren atención.
=====================================================================
Marketing: --- Calidad de Datos ---
--- Valores Nulos por Columna ---
id_campanha     0
producto        0
canal           0
costo           0
fecha_inicio    0
fecha_fin       0
dtype: int64

Cantidad de registros duplicados: 0

--- Resumen de Calidad de Datos ---
El dataset no presenta valores nulos ni duplicados iniciales.
=====================================================================

# EDA Automatizados

In [ ]:
# Instalar librería
! pip install ydata-profiling

Collecting ydata-profiling
  Downloading ydata_profiling-4.18.3-py2.py3-none-any.whl.metadata (23 kB)
Requirement already satisfied: scipy<1.17,>=1.8 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.16.3)
Requirement already satisfied: pandas!=1.4.0,<3.0,>1.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.2.2)
Requirement already satisfied: matplotlib<=3.10,>=3.5 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.10.0)
Requirement already satisfied: pydantic<3,>=2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.12.3)
Requirement already satisfied: PyYAML<6.1,>=6.0.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (6.0.3)
Requirement already satisfied: jinja2<3.2,>=3.1.6 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (3.1.6)
Collecting visions<0.8.2,>=0.7.5 (from visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading visions-0.8.1-py3-none-any.whl.metadata (11 kB)
Requirement already satisfied: numpy<2.4,>=1.22 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.0.2)
Collecting minify-html>=0.15.0 (from ydata-profiling)
  Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (18 kB)
Collecting filetype>=1.0.0 (from ydata-profiling)
  Downloading filetype-1.2.0-py2.py3-none-any.whl.metadata (6.5 kB)
Collecting phik<0.13,>=0.12.5 (from ydata-profiling)
  Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl.metadata (5.6 kB)
Requirement already satisfied: requests<3,>=2.32.0 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (2.32.4)
Requirement already satisfied: tqdm<5,>=4.66.3 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.67.3)
Requirement already satisfied: seaborn<0.14,>=0.10.1 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.13.2)
Collecting multimethod<2,>=1.4 (from ydata-profiling)
  Downloading multimethod-1.12-py3-none-any.whl.metadata (9.6 kB)
Requirement already satisfied: statsmodels<1,>=0.13.2 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.14.6)
Requirement already satisfied: typeguard<5,>=4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (4.5.1)
Collecting imagehash==4.3.2 (from ydata-profiling)
  Downloading ImageHash-4.3.2-py2.py3-none-any.whl.metadata (8.4 kB)
Requirement already satisfied: wordcloud>=1.9.4 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (1.9.6)
Collecting dacite<2,>=1.9 (from ydata-profiling)
  Downloading dacite-1.9.2-py3-none-any.whl.metadata (17 kB)
Requirement already satisfied: numba<0.63,>=0.60 in /usr/local/lib/python3.12/dist-packages (from ydata-profiling) (0.60.0)
Requirement already satisfied: PyWavelets in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (1.9.0)
Requirement already satisfied: pillow in /usr/local/lib/python3.12/dist-packages (from imagehash==4.3.2->ydata-profiling) (11.3.0)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.12/dist-packages (from jinja2<3.2,>=3.1.6->ydata-profiling) (3.0.3)
Requirement already satisfied: contourpy>=1.0.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.3.3)
Requirement already satisfied: cycler>=0.10 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (0.12.1)
Requirement already satisfied: fonttools>=4.22.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (4.62.1)
Requirement already satisfied: kiwisolver>=1.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (1.5.0)
Requirement already satisfied: packaging>=20.0 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (26.0)
Requirement already satisfied: pyparsing>=2.3.1 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (3.3.2)
Requirement already satisfied: python-dateutil>=2.7 in /usr/local/lib/python3.12/dist-packages (from matplotlib<=3.10,>=3.5->ydata-profiling) (2.9.0.post0)
Requirement already satisfied: llvmlite<0.44,>=0.43.0dev0 in /usr/local/lib/python3.12/dist-packages (from numba<0.63,>=0.60->ydata-profiling) (0.43.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas!=1.4.0,<3.0,>1.5->ydata-profiling) (2026.1)
Requirement already satisfied: joblib>=0.14.1 in /usr/local/lib/python3.12/dist-packages (from phik<0.13,>=0.12.5->ydata-profiling) (1.5.3)
Requirement already satisfied: annotated-types>=0.6.0 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.4 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (2.41.4)
Requirement already satisfied: typing-extensions>=4.14.1 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (4.15.0)
Requirement already satisfied: typing-inspection>=0.4.2 in /usr/local/lib/python3.12/dist-packages (from pydantic<3,>=2->ydata-profiling) (0.4.2)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3,>=2.32.0->ydata-profiling) (2026.2.25)
Requirement already satisfied: patsy>=0.5.6 in /usr/local/lib/python3.12/dist-packages (from statsmodels<1,>=0.13.2->ydata-profiling) (1.0.2)
Requirement already satisfied: attrs>=19.3.0 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (26.1.0)
Requirement already satisfied: networkx>=2.4 in /usr/local/lib/python3.12/dist-packages (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling) (3.6.1)
Collecting puremagic (from visions<0.8.2,>=0.7.5->visions[type_image_path]<0.8.2,>=0.7.5->ydata-profiling)
  Downloading puremagic-2.2.0-py3-none-any.whl.metadata (7.3 kB)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.7->matplotlib<=3.10,>=3.5->ydata-profiling) (1.17.0)
Downloading ydata_profiling-4.18.3-py2.py3-none-any.whl (400 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 400.8/400.8 kB 28.1 MB/s eta 0:00:00
Downloading ImageHash-4.3.2-py2.py3-none-any.whl (296 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 296.7/296.7 kB 23.5 MB/s eta 0:00:00
Downloading dacite-1.9.2-py3-none-any.whl (16 kB)
Downloading filetype-1.2.0-py2.py3-none-any.whl (19 kB)
Downloading minify_html-0.18.1-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (3.1 MB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 79.5 MB/s eta 0:00:00
Downloading multimethod-1.12-py3-none-any.whl (10 kB)
Downloading phik-0.12.5-cp312-cp312-manylinux_2_24_x86_64.manylinux_2_28_x86_64.whl (679 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 679.7/679.7 kB 47.9 MB/s eta 0:00:00
Downloading visions-0.8.1-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 9.5 MB/s eta 0:00:00
Downloading puremagic-2.2.0-py3-none-any.whl (71 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 72.0/72.0 kB 6.7 MB/s eta 0:00:00
Installing collected packages: minify-html, filetype, puremagic, multimethod, dacite, imagehash, visions, phik, ydata-profiling
Successfully installed dacite-1.9.2 filetype-1.2.0 imagehash-4.3.2 minify-html-0.18.1 multimethod-1.12 phik-0.12.5 puremagic-2.2.0 visions-0.8.1 ydata-profiling-4.18.3

## EDA Clientes

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df_clientes, title="EDA Report Clientes", explorative=True)
# profile.to_notebook_iframe()
profile.to_file("ydata_report_clientes.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

100%|██████████| 5/5 [00:00<00:00, 61.98it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## EDA Ventas

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df_ventas, title="EDA Report Ventas", explorative=True)
# profile.to_notebook_iframe()
profile.to_file("ydata_report_ventas.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]
100%|██████████| 6/6 [00:00<00:00, 29.11it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]

## EDA Marketing

In [ ]:
from ydata_profiling import ProfileReport

profile = ProfileReport(df_marketing, title="EDA Report Marketing", explorative=True)
# profile.to_notebook_iframe()
profile.to_file("ydata_report_marketing.html")

Summarize dataset:   0%|          | 0/5 [00:00<?, ?it/s]

  0%|          | 0/6 [00:00<?, ?it/s]
100%|██████████| 6/6 [00:00<00:00, 47.46it/s]

Generate report structure:   0%|          | 0/1 [00:00<?, ?it/s]

Render HTML:   0%|          | 0/1 [00:00<?, ?it/s]

Export report to file:   0%|          | 0/1 [00:00<?, ?it/s]